name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/manati-frontend:latest

      - name: Deploy to Hostinger
        run: |
          sshpass -p ${{ secrets.HOSTINGER_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -p 65002 ${{ secrets.HOSTINGER_SSH_USERNAME }}@${{ secrets.HOSTINGER_SSH_HOST }} \
          "docker pull ${{ secrets.DOCKER_USERNAME }}/manati-frontend:latest && docker stop manati-frontend && docker rm manati-frontend && docker run -d --name manati-frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/manati-frontend:latest"
